#!/bin/sh

# needed for "Save and Apply" to restart pymultimonaprs
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pymultimonaprs[-1]
	add ucitrack pymultimonaprs
	set ucitrack.@pymultimonaprs[-1].init="pymultimonaprs"
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
